sudo: true
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:
  - git config --global user.name "TravisCI"
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla
  - dzil authordeps --missing | xargs cpanm --quiet --notest

install:
  - dzil listdeps --missing | xargs cpanm --quiet --notest

script: HARNESS_IS_VERBOSE=1 prove -v -Ilib t
